spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa

  sql:
    init:
      mode: always
      platform: h2
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  h2:
    console:
      path: /h2-console
      enabled: true