INSERT INTO DUMMY VALUES (1, 'allie');
INSERT INTO DUMMY VALUES (2, 'brian');
INSERT INTO DUMMY VALUES (3, 'chris');
INSERT INTO DUMMY VALUES (4, 'danny');
INSERT INTO DUMMY VALUES (5, 'eugene');

INSERT INTO MARKETS VALUES (1, 'BTC', '비트코인', 'bitcoin', 'N');
INSERT INTO MARKETS VALUES (2, 'ETH', '이더리움', 'eth', 'N');
INSERT INTO MARKETS VALUES (3, 'XRP', '리플', 'ripple', 'N');
INSERT INTO MARKETS VALUES (4, 'TRX', '트론', 'tron', 'N');
