spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/crypto-automation'
    username: root
    password:

  sql:
    init:
      mode: never

  batch:
    job:
      enabled: true
      name: ${job.name:upBitSlackJob}